config/routes.rb
Parking::Application.routes.draw do

  match 'lots/delta' => 'lots#delta', :as => :delta
  
  resources :lots

  root :to => 'lots#index'

end

app/models/coordinate.rb
class Coordinate < ActiveRecord::Base
  attr_accessible :order, :x, :y
  belongs_to :lots
end

app/models/lot.rb
class Lot < ActiveRecord::Base
  attr_accessible :name, :cars, :total_spots, :type_type
  
  validates_presence_of :total_spots, :cars, :type_type

  has_many :coordinates
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  # GET /lots
  # GET /lots.json
  def index
    @lots = Lot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lots }
    end
  end

  def delta
    @lot = Lot.find_by_name(params[:name])

    respond_to do |format|
      if @lot.update_attributes(:cars => (@lot.cars + Integer(params[:delta])))
        format.html { redirect_to @lot, notice: 'Lot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /lots/1
  # GET /lots/1.json
  def show
    @lot = Lot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lot }
    end
  end

  # GET /lots/new
  # GET /lots/new.json
  def new
    @lot = Lot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lot }
    end
  end

  # GET /lots/1/edit
  def edit
    @lot = Lot.find(params[:id])
  end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(params[:lot])

    respond_to do |format|
      if @lot.save
        format.html { redirect_to lots_path, notice: 'Lot was successfully created.' }
        format.json { render json: @lot, status: :created, location: @lot }
      else
        format.html { render action: "new" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lots/1
  # PUT /lots/1.json
  def update
    @lot = Lot.find(params[:id])

    respond_to do |format|
      if @lot.update_attributes(params[:lot])
        format.html { redirect_to @lot, notice: 'Lot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot = Lot.find(params[:id])
    @lot.destroy

    respond_to do |format|
      format.html { redirect_to lots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lots_helper.rb
module LotsHelper
    def get_coords(lot)
        # returns a comma separted list of coordinates for use in an html map.
        # i.e. x1,y1,x2,y2,...etc
        coordinates = lot.coordinates.collect do |coord|
            "#{coord.x},#{coord.y}"
        end

        coordinates.join(',')
    end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Parking
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    /= favicon_link_tag "favicon.ico"
    = csrf_meta_tags
    %meta{id:"viewport",
          name:"viewport",
          content:"width=device-width; initial-scale=1; maximum-scale=1; user-scalable=0;"}
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %ul.nav
            %li
              %span.brand= link_to "acmX - Parking", root_path
            %li= link_to 'Parking Lots', lots_path, :title => "Click to see all parking lots"
            /%li.divider-vertical
            /%li= link_to "Login", :login
            /%li=link_to "Register", :register
    #body
      - if params[:controller] = "lots"
        .span2
          .sidebar-nav.sidebar-nav-fixed
            %fieldset
              %legend Parking Lots

              %table.table.table-striped
                %thead
                  %tr
                    %th Name
                    %th Open Spots
                    %th 
                %tbody
                  - Lot.all.each do |lot|
                    %tr
                      %td
                        %span{style:"background-color:#{(lot.type_type == 'commuter') ? '#ED0' : '#09F' };"} &nbsp;
                        = lot.name
                      %td= lot.total_spots-lot.cars
                      %td= link_to "Open", lot_path(lot), class: "btn btn-mini"
            = link_to "Add Lot (for now)", new_lot_path
            
      .span2
      .span8
        #flashcontainer
          - flash.each do |key, msg|
            - if key == :information
              .alert.alert-info
                %button.close{:'data-dismiss' => "alert"} ×
                = msg
            - if key == :notice
              .alert.alert-success
                %button.close{:'data-dismiss' => "alert"} ×
                = msg
            - if key == :warning
              .alert
                %button.close{:'data-dismiss' => "alert"} ×
                = msg
            - if key == :error
              .alert.alert-error
                %button.close{:'data-dismiss' => "alert"} ×
                = msg
        = yield

app/views/lots/_form.html.haml
= form_for(@lot) do |f|
  %fieldset
    %legend
      = controller.action_name.capitalize
      Lot

    - if @lot.errors.any?
      #error_explanation
        %h2
          = pluralize(@lot.errors.count, "error")
          prohibited this lot from being saved:
        %ul
          - @lot.errors.full_messages.each do |msg|
            %li= msg
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :total_spots, "Total Spots"
      = f.number_field :total_spots
    .field
      = f.label :cars
      = f.number_field :cars
    .field
      = f.label :type_type, "Type"
      = f.select(:type_type, %w[ commuter general ], { :include_blank => false })
    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', lots_path, :class => 'btn'

app/views/lots/edit.html.haml
= render 'form'

app/views/lots/index.html.haml
.mapview
  %map{name:"lot_spots"}
    - @lots.each do |lot|
      %area{shape:"poly",coords:get_coords(lot),href:lot_path(lot)}

  = image_tag "parking.png", usemap: "#lot_spots", ondragstart: "return false" #the ondragstart thing is to prevent draggin the image (better ux)
  %hr/
  %span.legend-badge{style:"background-color:#ED0;"} &nbsp; &nbsp; &nbsp;
  Commuter &nbsp; &nbsp;
  %span.legend-badge{style:"background-color:#09F;"} &nbsp; &nbsp; &nbsp;
  General

app/views/lots/new.html.haml
= render 'form'

app/views/lots/show.html.haml
%fieldset
  %legend
    = @lot.name
    %small
      (
      = @lot.type_type
      )

%p
  %b Total Spots:
  = @lot.total_spots
%p
  %b Cars in Lot:
  = @lot.cars

.form-actions
  = link_to 'Edit', edit_lot_path(@lot), :class => 'btn'
  = link_to 'Cancel', lots_path, :class => 'btn'